baseURL = 'https://shaigeva.github.io/'
languageCode = 'en-us'
title = "Shai Geva"

[params]
author = "Shai Geva"

[params.homeInfoParams]
Title = "Shai Geva (UNDER CONSTRUCTION)"

Content = """
I write about code.

Code is good.
"""


[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"
