baseURL = 'https://shaigeva.github.io/'
languageCode = 'en-us'
title = "Shai Geva"

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[menu]

[[menu.main]]
name = "About"
url = "about"
weight = 1

[[menu.main]]
name = "Talks"
url = "talks"
weight = 2

[[menu.main]]
name = "Search"
url = "search/"
weight = 3

[params]
author = "Shai Geva"

[params.homeInfoParams]
Title = "Optimistic coding (UNDER CONSTRUCTION)"

Content = """
Hey!

My name is Shai Geva.

I've been writing code for over 20 years, and I remain optimistic about our ability
to create stuff that work and are not too complex to maintain.

I write about code, tests (a lot), ai and other stuff.

Look around, and ping me on social to tell me if you found something useful!
"""

# Needed to enable the search page.
[outputs]
home = ["HTML", "RSS", "JSON"]


[[params.socialIcons]]
name = "github"
title = "Github profile"
url = "https://github.com/shaigeva"

[[params.socialIcons]]
name = "X"
title = "Follow on Twitter / X"
url = "https://x.com/shai_ge"

[[params.socialIcons]]
name = "Linkedin"
title = "Linkedin profile"
url = "https://www.linkedin.com/in/shai-geva-bb51404/"
