baseURL = 'https://shaigeva.github.io/'
languageCode = 'en-us'
title = "Shai Geva"

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[menu]

[[menu.main]]
name = "About"
url = "about"
weight = 1

[[menu.main]]
name = "Search"
url = "search/"
weight = 2

[params]
author = "Shai Geva"

[params.homeInfoParams]
Title = "Shai Geva (UNDER CONSTRUCTION)"

Content = """
I write about code.

Code is good.
"""

# Needed to enable the search page.
[outputs]
home = ["HTML", "RSS", "JSON"]


[[params.socialIcons]]
name = "github"
title = "Github profile"
url = "https://github.com/shaigeva"

[[params.socialIcons]]
name = "X"
title = "Follow on Twitter / X"
url = "https://x.com/shai_ge"

[[params.socialIcons]]
name = "Linkedin"
title = "Linkedin profile"
url = "https://www.linkedin.com/in/shai-geva-bb51404/"
