baseURL = 'https://shaigeva.com/'
languageCode = 'en-us'
title = "Shai Geva"

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[menu]

[[menu.main]]
name = "About"
url = "about"
weight = 1

[[menu.main]]
name = "Talks"
url = "talks"
weight = 2

[[menu.main]]
name = "Search"
url = "search/"
weight = 3

[params]
author = "Shai Geva"
env = "production"

[services]
[services.googleAnalytics]
id = 'G-YWC9X8YE9C'

[params.homeInfoParams]
Title = "Optimistic Coding Craftsmanship"

Content = """
Hey there! My name is Shai Geva.

&nbsp;


I've been writing code for over 20 years, and I remain optimistic about our ability
to create stuff that works and are not too complex to maintain.

&nbsp;

I've always liked the craftsmanship itself in software development, and I think these crazy times (craziest I've ever seen,
certainly) give us a sort-of "new chapter" in our craft - we don't know where it's going, but there are a lot of
exciting new things to learn and to create.

&nbsp;

I write about AI, code, tests and other stuff (noting - the site is new so not all posts have been uploaded yet,
they will be added in the next few weeks) .

&nbsp;

Look around, and ping me on social to tell me if you found something useful!
"""

# Needed to enable the search page.
[outputs]
home = ["HTML", "RSS", "JSON"]


[[params.socialIcons]]
name = "github"
title = "Github profile"
url = "https://github.com/shaigeva"

[[params.socialIcons]]
name = "X"
title = "Follow on Twitter / X"
url = "https://x.com/shai_ge"

[[params.socialIcons]]
name = "Linkedin"
title = "Linkedin profile"
url = "https://www.linkedin.com/in/shai-geva-bb51404/"
