baseURL = 'https://shaigeva.github.io/'
languageCode = 'en-us'
title = "Shai's site"

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"


[params.author]
  avatar = "shai_avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Shai Geva (UNDER CONSTRUCTION)"
  name = "Shai Geva"
  description = "I write about code"
