baseURL = 'https://shaigeva.github.io/'
languageCode = 'en-us'
title = "Shai Geva"

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[menu]

[[menu.main]]
name = "About"
url = "about"
weight = 1

[[menu.main]]
name = "Search"
url = "search/"
weight = 2

[params]
author = "Shai Geva"

[params.homeInfoParams]
Title = "Shai Geva (UNDER CONSTRUCTION)"

Content = """
I write about code.

Code is good.
"""

# Needed to enable the search page.
[outputs]
home = ["HTML", "RSS", "JSON"]
